/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ct417_assignment_1_a_bird;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
